SELECT AVG(S.home_prob) as home_prob,SUM((H.avg > A.avg)*(M.home_team_score > M.away_team_score)+(H.avg < A.avg)*(M.home_team_score < M.away_team_score))/COUNT(M.id) as last_prob FROM 
match_info M,
(SELECT M.id,(P1.score+P2.score+P3.score+P4.score+P5.score)/5 as avg FROM (SELECT id FROM match_info)M,
(SELECT M.id,P.overall_rating as score FROM match_info AS M,player_attributes AS P WHERE M.home_player_1 = P.player_api_id AND P.id in  (SELECT MIN(P.id) FROM  match_info M,player_attributes P WHERE M.home_player_1 = P.player_api_id AND (P.date<=M.date) GROUP BY P.player_api_id ) ) P1, 
(SELECT M.id,P.overall_rating as score FROM match_info AS M,player_attributes AS P WHERE M.home_player_2 = P.player_api_id AND P.id in  (SELECT MIN(P.id) FROM  match_info M,player_attributes P WHERE M.home_player_2 = P.player_api_id AND (P.date<=M.date) GROUP BY P.player_api_id ) ) P2, 
(SELECT M.id,P.overall_rating as score FROM match_info AS M,player_attributes AS P WHERE M.home_player_3 = P.player_api_id AND P.id in  (SELECT MIN(P.id) FROM  match_info M,player_attributes P WHERE M.home_player_3 = P.player_api_id AND (P.date<=M.date) GROUP BY P.player_api_id ) ) P3, 
(SELECT M.id,P.overall_rating as score FROM match_info AS M,player_attributes AS P WHERE M.home_player_4 = P.player_api_id AND P.id in  (SELECT MIN(P.id) FROM  match_info M,player_attributes P WHERE M.home_player_4 = P.player_api_id AND (P.date<=M.date) GROUP BY P.player_api_id ) ) P4, 
(SELECT M.id,P.overall_rating as score FROM match_info AS M,player_attributes AS P WHERE M.home_player_5 = P.player_api_id AND P.id in  (SELECT MIN(P.id) FROM  match_info M,player_attributes P WHERE M.home_player_5 = P.player_api_id AND (P.date<=M.date) GROUP BY P.player_api_id ) ) P5
WHERE M.id = P1.id AND M.id = P2.id AND M.id = P3.id AND M.id = P4.id AND M.id = P5.id) AS H,
(SELECT M.id,(P1.score+P2.score+P3.score+P4.score+P5.score)/5 as avg FROM (SELECT id FROM match_info)M,
(SELECT M.id,P.overall_rating as score FROM match_info AS M,player_attributes AS P WHERE M.away_player_1 = P.player_api_id AND P.id in  (SELECT MIN(P.id) FROM  match_info M,player_attributes P WHERE M.away_player_1 = P.player_api_id AND (P.date<=M.date) GROUP BY P.player_api_id ) ) P1, 
(SELECT M.id,P.overall_rating as score FROM match_info AS M,player_attributes AS P WHERE M.away_player_2 = P.player_api_id AND P.id in  (SELECT MIN(P.id) FROM  match_info M,player_attributes P WHERE M.away_player_2 = P.player_api_id AND (P.date<=M.date) GROUP BY P.player_api_id ) ) P2, 
(SELECT M.id,P.overall_rating as score FROM match_info AS M,player_attributes AS P WHERE M.away_player_3 = P.player_api_id AND P.id in  (SELECT MIN(P.id) FROM  match_info M,player_attributes P WHERE M.away_player_3 = P.player_api_id AND (P.date<=M.date) GROUP BY P.player_api_id ) ) P3, 
(SELECT M.id,P.overall_rating as score FROM match_info AS M,player_attributes AS P WHERE M.away_player_4 = P.player_api_id AND P.id in  (SELECT MIN(P.id) FROM  match_info M,player_attributes P WHERE M.away_player_4 = P.player_api_id AND (P.date<=M.date) GROUP BY P.player_api_id ) ) P4, 
(SELECT M.id,P.overall_rating as score FROM match_info AS M,player_attributes AS P WHERE M.away_player_5 = P.player_api_id AND P.id in  (SELECT MIN(P.id) FROM  match_info M,player_attributes P WHERE M.away_player_5 = P.player_api_id AND (P.date<=M.date) GROUP BY P.player_api_id ) ) P5
WHERE M.id = P1.id AND M.id = P2.id AND M.id = P3.id AND M.id = P4.id AND M.id = P5.id) AS A,
(SELECT SUM(home_team_score>away_team_score)/COUNT(id) as home_prob FROM match_info) AS S 
WHERE M.id = H.id AND M.id = A.id;